# Generated by Django 3.2.3 on 2022-11-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_be', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='React',
            new_name='ReactView',
        ),
    ]
